repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-ast
    - repo: https://github.com/psf/black-pre-commit-mirror
      rev: 23.12.1
      hooks:
          - id: black
          - id: black-jupyter
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
